/** Generated by tools/gen_schema.py from the tracker. Do not edit by hand.
 *  formulas: grey-column formulas for new rows ({r} = row number)
 *  formats:  columns kept as text / dates / money
 *  columns:  expected headers per tab (Setup checks the tracker against these) */
var SCHEMA = {
 "formulas": {
  "Producers": {
   "Submissions": "=COUNTIF(Submissions!B:B,A{r})"
  },
  "Submissions": {
   "Flock_Name": "=IFERROR(INDEX(Producers!B:B,MATCH(B{r},Producers!A:A,0))&\"\",\"\")",
   "NSIP_Animals": "=COUNTIFS(Animals!B:B,A{r},Animals!E:E,\"<>\")",
   "Animals_Listed": "=COUNTIF(Animals!B:B,A{r})",
   "TSUs_Received": "=COUNTIFS(Animals!B:B,A{r},Animals!N:N,\"Y\")",
   "Photos": "=COUNTIF(Photos!B:B,A{r})",
   "Invoice_ID": "=IF(Q{r}=\"\",\"\",\"INV-\"&A{r})"
  },
  "Animals": {
   "Photos": "=COUNTIF(Photos!A:A,A{r})",
   "Producer_ID": "=IFERROR(INDEX(Submissions!B:B,MATCH(B{r},Submissions!A:A,0))&\"\",\"\")",
   "Genotyped": "=IF(P{r}=\"Complete\",\"Y\",\"N\")",
   "Reported_Sire_Status": "=IF(J{r}=\"\",\"\",IF(COUNTIFS(Candidate_Parents!A:A,U{r},Candidate_Parents!C:C,J{r})+COUNTIFS(Candidate_Parents!A:A,U{r},Candidate_Parents!D:D,J{r})+COUNTIFS(Candidate_Parents!A:A,U{r},Candidate_Parents!E:E,J{r})>0,\"Genotyped\",IF(COUNTIFS(B:B,B{r},C:C,J{r},P:P,\"<>Not received\")>0,\"In this submission\",\"Not genotyped\")))",
   "Reported_Dam_Status": "=IF(K{r}=\"\",\"\",IF(COUNTIFS(Candidate_Parents!A:A,U{r},Candidate_Parents!C:C,K{r})+COUNTIFS(Candidate_Parents!A:A,U{r},Candidate_Parents!D:D,K{r})+COUNTIFS(Candidate_Parents!A:A,U{r},Candidate_Parents!E:E,K{r})>0,\"Genotyped\",IF(COUNTIFS(B:B,B{r},C:C,K{r},P:P,\"<>Not received\")>0,\"In this submission\",\"Not genotyped\")))",
   "Age_At_Receipt": "=IF(H{r}=\"\",\"\",IFERROR(YEAR(IF(INDEX(Submissions!Q:Q,MATCH(B{r},Submissions!A:A,0))=\"\",TODAY(),INDEX(Submissions!Q:Q,MATCH(B{r},Submissions!A:A,0))))-VALUE(LEFT(H{r},4)),\"\"))",
   "Proven": "=IF(AA{r}=\"\",\"\",IF(AA{r}>=INDEX(Settings!B:B,MATCH(\"Proven_Min_Age\",Settings!A:A,0)),\"Y\",\"N\"))",
   "CS_Program": "=IF(IF(AC{r}<>\"\",AC{r},IFERROR(INDEX(Submissions!U:U,MATCH(B{r},Submissions!A:A,0))&\"\",\"\"))=\"\",\"\",IF(AND(IFERROR(INDEX(Cost_Share!H:H,MATCH(IF(AC{r}<>\"\",AC{r},IFERROR(INDEX(Submissions!U:U,MATCH(B{r},Submissions!A:A,0))&\"\",\"\")),Cost_Share!A:A,0))&\"\",\"\")=\"Y\",E{r}=\"\"),\"\",IF(AC{r}<>\"\",AC{r},IFERROR(INDEX(Submissions!U:U,MATCH(B{r},Submissions!A:A,0))&\"\",\"\"))))",
   "CS_Level": "=IF(AE{r}=\"\",\"None\",IF(AD{r}<>\"\",AD{r},IF(AB{r}=\"Y\",\"Full\",\"Partial\")))"
  },
  "Batches": {
   "Samples": "=COUNTIF(Animals!O:O,A{r})+COUNTIF(Replacements!G:G,A{r})"
  },
  "Result_Key": {
   "Key": "=B{r}&\"|\"&C{r}"
  },
  "Invoices": {
   "Flock_Name": "=IFERROR(INDEX(Submissions!C:C,MATCH(B{r},Submissions!A:A,0))&\"\",\"\")",
   "Animals_Billed": "=SUMIFS(Invoice_Lines!E:E,Invoice_Lines!A:A,A{r},Invoice_Lines!C:C,\"GENO\")",
   "Subtotal": "=SUMIFS(Invoice_Lines!G:G,Invoice_Lines!A:A,A{r})",
   "Submission_Program": "=IFERROR(INDEX(Submissions!U:U,MATCH(B{r},Submissions!A:A,0))&\"\",\"\")",
   "Partner_Organization": "=IF(G{r}=\"\",\"\",IFERROR(INDEX(Cost_Share!C:C,MATCH(G{r},Cost_Share!A:A,0))&\"\",\"\"))",
   "Cost_Share_Total": "=SUMIFS(Invoice_Lines!J:J,Invoice_Lines!A:A,A{r})",
   "Producer_Due": "=F{r}-I{r}",
   "Full_Covered": "=SUMIFS(Invoice_Lines!E:E,Invoice_Lines!A:A,A{r},Invoice_Lines!L:L,\"Full\")",
   "Partial_Covered": "=SUMIFS(Invoice_Lines!E:E,Invoice_Lines!A:A,A{r},Invoice_Lines!L:L,\"Partial\")"
  },
  "Invoice_Lines": {
   "Amount": "=E{r}*F{r}",
   "Cost_Share_Eligible": "=IFERROR(INDEX(Services!E:E,MATCH(C{r},Services!A:A,0))&\"\",\"N\")",
   "Partner_Share": "=IF(OR(H{r}<>\"Y\",I{r}=\"\"),0,IFERROR(MIN(G{r},E{r}*IF(O{r}<>\"\",O{r},IF(L{r}=\"Full\",INDEX(Cost_Share!G:G,MATCH(I{r},Cost_Share!A:A,0)),IF(L{r}=\"Partial\",INDEX(Cost_Share!F:F,MATCH(I{r},Cost_Share!A:A,0)),0)))),0))",
   "Invoice_Date": "=IFERROR(INDEX(Invoices!D:D,MATCH(A{r},Invoices!A:A,0)),\"\")",
   "Invoice_Status": "=IFERROR(INDEX(Invoices!K:K,MATCH(A{r},Invoices!A:A,0))&\"\",\"\")"
  },
  "Partner_Billing": {
   "Partner_Organization": "=IFERROR(INDEX(Cost_Share!C:C,MATCH(B{r},Cost_Share!A:A,0))&\"\",\"\")",
   "Full_Animals": "=SUMPRODUCT(Invoice_Lines!$E$2:$E$5000,(Invoice_Lines!$I$2:$I$5000=B{r})*(Invoice_Lines!$M$2:$M$5000>=D{r})*(Invoice_Lines!$M$2:$M$5000<=E{r})*((Invoice_Lines!$N$2:$N$5000=\"Sent\")+(Invoice_Lines!$N$2:$N$5000=\"Paid\"))*((Invoice_Lines!$P$2:$P$5000=\"\")+(Invoice_Lines!$P$2:$P$5000=A{r}))*(Invoice_Lines!$L$2:$L$5000=\"Full\"))",
   "Partial_Animals": "=SUMPRODUCT(Invoice_Lines!$E$2:$E$5000,(Invoice_Lines!$I$2:$I$5000=B{r})*(Invoice_Lines!$M$2:$M$5000>=D{r})*(Invoice_Lines!$M$2:$M$5000<=E{r})*((Invoice_Lines!$N$2:$N$5000=\"Sent\")+(Invoice_Lines!$N$2:$N$5000=\"Paid\"))*((Invoice_Lines!$P$2:$P$5000=\"\")+(Invoice_Lines!$P$2:$P$5000=A{r}))*(Invoice_Lines!$L$2:$L$5000=\"Partial\"))",
   "Amount_Due": "=SUMPRODUCT(Invoice_Lines!$J$2:$J$5000,(Invoice_Lines!$I$2:$I$5000=B{r})*(Invoice_Lines!$M$2:$M$5000>=D{r})*(Invoice_Lines!$M$2:$M$5000<=E{r})*((Invoice_Lines!$N$2:$N$5000=\"Sent\")+(Invoice_Lines!$N$2:$N$5000=\"Paid\"))*((Invoice_Lines!$P$2:$P$5000=\"\")+(Invoice_Lines!$P$2:$P$5000=A{r})))"
  }
 },
 "formats": {
  "Settings": {
   "text": [],
   "date": [],
   "money": []
  },
  "Producers": {
   "text": [
    "Producer_ID",
    "NSIP_Flock_ID",
    "Phone"
   ],
   "date": [
    "First_Submitted"
   ],
   "money": []
  },
  "Submissions": {
   "text": [
    "Submission_ID",
    "Producer_ID",
    "Private_Link_Token"
   ],
   "date": [
    "Submitted_Date",
    "Signed_Date",
    "Received_Date",
    "Results_Released_Date",
    "Research_Withdrawn_Date",
    "Last_Reminder_Date"
   ],
   "money": []
  },
  "Animals": {
   "text": [
    "Animal_Key",
    "Submission_ID",
    "Flock_Tag",
    "EID",
    "NSIP_ID",
    "TSU_Barcode",
    "Year_of_Birth",
    "Reported_Sire",
    "Reported_Dam"
   ],
   "date": [],
   "money": []
  },
  "Photos": {
   "text": [
    "Animal_Key",
    "Submission_ID"
   ],
   "date": [
    "Uploaded_Date",
    "Archived_Date"
   ],
   "money": []
  },
  "Batches": {
   "text": [
    "Batch_ID"
   ],
   "date": [
    "Created_Date",
    "Shipped_Date",
    "Results_Received_Date"
   ],
   "money": []
  },
  "Replacements": {
   "text": [
    "Replacement_ID",
    "Animal_Key",
    "Submission_ID",
    "Original_TSU",
    "New_TSU",
    "Original_Batch",
    "New_Batch"
   ],
   "date": [
    "Requested_Date",
    "Received_Date"
   ],
   "money": []
  },
  "Conditions": {
   "text": [],
   "date": [],
   "money": []
  },
  "Result_Key": {
   "text": [
    "Call"
   ],
   "date": [],
   "money": []
  },
  "Results": {
   "text": [
    "Animal_Key",
    "Submission_ID",
    "Call",
    "Batch"
   ],
   "date": [
    "Run_Date"
   ],
   "money": []
  },
  "Parentage": {
   "text": [
    "Animal_Key",
    "Submission_ID",
    "Reported_Sire",
    "Reported_Dam",
    "Sire_Assigned",
    "Dam_Assigned"
   ],
   "date": [],
   "money": []
  },
  "Candidate_Parents": {
   "text": [
    "Producer_ID",
    "Animal_Key",
    "Flock_Tag",
    "EID",
    "NSIP_ID",
    "Year_of_Birth",
    "Genotyped_In"
   ],
   "date": [],
   "money": []
  },
  "Services": {
   "text": [
    "Service_ID"
   ],
   "date": [],
   "money": [
    "Unit_Price"
   ]
  },
  "Cost_Share": {
   "text": [
    "Program_ID"
   ],
   "date": [
    "Start_Date",
    "End_Date"
   ],
   "money": [
    "Partial_Share",
    "Full_Share"
   ]
  },
  "Invoices": {
   "text": [
    "Invoice_ID",
    "Submission_ID",
    "Check_Number"
   ],
   "date": [
    "Invoice_Date",
    "Sent_Date",
    "Paid_Date"
   ],
   "money": [
    "Subtotal",
    "Cost_Share_Total",
    "Producer_Due"
   ]
  },
  "Invoice_Lines": {
   "text": [
    "Invoice_ID",
    "Service_ID",
    "Cost_Share_Program",
    "Partner_Bill"
   ],
   "date": [
    "Invoice_Date"
   ],
   "money": [
    "Unit_Price",
    "Amount",
    "Partner_Share",
    "Share_Per_Unit"
   ]
  },
  "Partner_Billing": {
   "text": [
    "Partner_Invoice_ID",
    "Program_ID",
    "Check_Number"
   ],
   "date": [
    "Period_Start",
    "Period_End",
    "Sent_Date",
    "Paid_Date"
   ],
   "money": [
    "Amount_Due"
   ]
  },
  "Email_Templates": {
   "text": [],
   "date": [],
   "money": []
  },
  "Email_Log": {
   "text": [],
   "date": [],
   "money": []
  }
 },
 "columns": {
  "Settings": [
   "Setting",
   "Value",
   "Notes"
  ],
  "Producers": [
   "Producer_ID",
   "Flock_Name",
   "Contact_Name",
   "Email",
   "Phone",
   "Mailing_Address",
   "NSIP_Flock_ID",
   "First_Submitted",
   "Submissions",
   "Notes"
  ],
  "Submissions": [
   "Submission_ID",
   "Producer_ID",
   "Flock_Name",
   "Submitted_Date",
   "Breed",
   "NSIP_Animals",
   "Research_Use",
   "Signed_By",
   "Signed_Date",
   "Producer_Notes",
   "Form_File",
   "Private_Link_Token",
   "Animals_Listed",
   "TSUs_Received",
   "Photos",
   "Status",
   "Received_Date",
   "Results_Released_Date",
   "Invoice_ID",
   "Staff_Notes",
   "Cost_Share_Program",
   "Signature_Method",
   "Research_Withdrawn_Date",
   "Drive_Folder",
   "Results_PDF",
   "Results_Excel",
   "Reminders_Sent",
   "Last_Reminder_Date",
   "Contact_On_Form"
  ],
  "Animals": [
   "Animal_Key",
   "Submission_ID",
   "Flock_Tag",
   "EID",
   "NSIP_ID",
   "TSU_Barcode",
   "Sex",
   "Year_of_Birth",
   "Role",
   "Reported_Sire",
   "Reported_Dam",
   "Test_Conditions",
   "Test_Parentage",
   "Received",
   "Batch",
   "Sample_Status",
   "Replaced_TSU",
   "Photos",
   "Notes",
   "Received_By",
   "Producer_ID",
   "Genotyped",
   "Reported_Sire_Status",
   "Reported_Dam_Status",
   "Breed",
   "Birth_Flock",
   "Age_At_Receipt",
   "Proven",
   "CS_Override_Program",
   "CS_Override_Level",
   "CS_Program",
   "CS_Level",
   "Billed_On"
  ],
  "Photos": [
   "Animal_Key",
   "Submission_ID",
   "Photo_No",
   "Drive_Link",
   "Uploaded_Date",
   "Archived_Date",
   "Archive_Location"
  ],
  "Batches": [
   "Batch_ID",
   "Lab",
   "Status",
   "Created_Date",
   "Created_By",
   "Shipped_Date",
   "Samples",
   "Results_Received_Date",
   "Export_File",
   "Notes"
  ],
  "Replacements": [
   "Replacement_ID",
   "Animal_Key",
   "Submission_ID",
   "Reason",
   "Original_TSU",
   "New_TSU",
   "Original_Batch",
   "Requested_Date",
   "Received",
   "Received_Date",
   "Received_By",
   "New_Batch",
   "Notes"
  ],
  "Conditions": [
   "Condition_ID",
   "Display_Name",
   "Gene_Marker",
   "Show_On_Web",
   "Active",
   "Sort_Order",
   "Call_Is",
   "Explanation"
  ],
  "Result_Key": [
   "Key",
   "Condition_ID",
   "Call",
   "Result_Label",
   "Category",
   "Meaning"
  ],
  "Results": [
   "Animal_Key",
   "Submission_ID",
   "Condition_ID",
   "Genotype",
   "Call",
   "Result_Label",
   "Category",
   "Batch",
   "Run_Date",
   "Released"
  ],
  "Parentage": [
   "Animal_Key",
   "Submission_ID",
   "Reported_Sire",
   "Sire_Result",
   "Sire_Assigned",
   "Reported_Dam",
   "Dam_Result",
   "Dam_Assigned",
   "Notes",
   "Released"
  ],
  "Candidate_Parents": [
   "Producer_ID",
   "Animal_Key",
   "Flock_Tag",
   "EID",
   "NSIP_ID",
   "Sex",
   "Year_of_Birth",
   "Genotyped_In",
   "Active",
   "Notes"
  ],
  "Services": [
   "Service_ID",
   "Description",
   "Unit_Price",
   "Unit",
   "Cost_Share_Eligible",
   "Active",
   "Notes"
  ],
  "Cost_Share": [
   "Program_ID",
   "Program_Name",
   "Partner_Organization",
   "Partner_Contact",
   "Partner_Email",
   "Partial_Share",
   "Full_Share",
   "Requires_NSIP",
   "Start_Date",
   "End_Date",
   "Active",
   "Notes"
  ],
  "Invoices": [
   "Invoice_ID",
   "Submission_ID",
   "Flock_Name",
   "Invoice_Date",
   "Animals_Billed",
   "Subtotal",
   "Submission_Program",
   "Partner_Organization",
   "Cost_Share_Total",
   "Producer_Due",
   "Status",
   "Sent_Date",
   "Paid_Date",
   "Check_Number",
   "Notes",
   "Full_Covered",
   "Partial_Covered",
   "PDF_Link"
  ],
  "Invoice_Lines": [
   "Invoice_ID",
   "Line_No",
   "Service_ID",
   "Description",
   "Qty",
   "Unit_Price",
   "Amount",
   "Cost_Share_Eligible",
   "Cost_Share_Program",
   "Partner_Share",
   "Notes",
   "Cost_Share_Level",
   "Invoice_Date",
   "Invoice_Status",
   "Share_Per_Unit",
   "Partner_Bill"
  ],
  "Partner_Billing": [
   "Partner_Invoice_ID",
   "Program_ID",
   "Partner_Organization",
   "Period_Start",
   "Period_End",
   "Full_Animals",
   "Partial_Animals",
   "Amount_Due",
   "Status",
   "Sent_Date",
   "Paid_Date",
   "Notes",
   "Check_Number",
   "PDF_Link"
  ],
  "Email_Templates": [
   "Email_ID",
   "Name",
   "Sent_When",
   "How_Sent",
   "Subject",
   "Body"
  ],
  "Email_Log": [
   "Sent_At",
   "Email_ID",
   "To",
   "Subject",
   "Submission_ID",
   "Sent_By",
   "Result"
  ]
 }
};
