"""Regenerate apps-script/Schema.gs from the tracker builder's schema export.
Run after changing the tracker's columns:  python3 tools/gen_schema.py path/to/tracker_schema.json"""
import json, sys, pathlib
src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else 'tracker_schema.json')
d = json.load(open(src))
out = pathlib.Path(__file__).resolve().parent.parent / 'apps-script' / 'Schema.gs'
out.write_text('/** Generated by tools/gen_schema.py from the tracker. Do not edit by hand.\n'
               ' *  formulas: grey-column formulas for new rows ({r} = row number)\n'
               ' *  formats:  columns kept as text / dates / money\n'
               ' *  columns:  expected headers per tab (Setup checks the tracker against these) */\n'
               'var SCHEMA = ' + json.dumps(d, indent=1) + ';\n')
print('wrote', out)
